# fly.toml app configuration file generated for yaas on 2024-01-29T19:59:49-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yaas"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8123
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
